[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6.2"
bincode = "1.3.3"
common = { path = "../common" }
glam = "0.20.5"
message-io = { version = "0.14.5", default_features = false, features = ["tcp"] }
serde = "1.0.137"
